workflows:
  ios_release:
    name: iOS Release (Pods repo-update)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    scripts:
      - name: Pre-build: Prepare plugins and install pods
        script: |
          set -e
          echo "[CI] Cleaning CocoaPods caches and previous lock/Pods"
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          echo "[CI] Running flutter pub get to regenerate .symlinks"
          flutter pub get
          echo "[CI] Bumping plugin podspec platform requirements to iOS 15.0"
          if [ -d .symlinks/plugins ]; then
            find .symlinks/plugins -name "*.podspec" -print0 | xargs -0 sed -i '' "s/platform :ios, '12.0'/platform :ios, '15.0'/g"
            find .symlinks/plugins -name "*.podspec" -print0 | xargs -0 sed -i '' "s/platform :ios, '13.0'/platform :ios, '15.0'/g"
            find .symlinks/plugins -name "*.podspec" -print0 | xargs -0 sed -i '' "s/platform :ios, '14.0'/platform :ios, '15.0'/g"
            # Also handle s.platform assignment style within podspecs
            find .symlinks/plugins -name "*.podspec" -print0 | xargs -0 sed -i '' -E "s/(s\.platform = :ios, ')[0-9]+\.[0-9]+'/\115.0'/g"
            find .symlinks/plugins -name "*.podspec" -print0 | xargs -0 sed -i '' -E "s/(spec\.platform = :ios, ')[0-9]+\.[0-9]+'/\115.0'/g"
          fi
          echo "[CI] Installing pods (repo update)"
          cd ios
          pod install --repo-update
          cd ..
      - name: Flutter build iOS (no codesign)
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/xcarchive.zip
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods
  ios_appstore_signed:
    name: iOS App Store Signed
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
      groups:
        - app_store_connect
        - signing
    scripts:
      - name: Pre-build: Prepare & install pods (signed)
        script: |
          set -e
          flutter pub get
          cd ios
          rm -f Podfile.lock
          pod install --repo-update
          cd ..
      - name: Set build number from pubspec
        script: |
          BUILD_NUMBER=$(grep '^version:' pubspec.yaml | cut -d'+' -f2)
          echo "Detected build number: $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist
      - name: Build signed IPA
        script: |
          flutter build ipa --release --export-options-plist=exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        ipa_path: build/ios/ipa/*.ipa
        submit_to_testflight: true
        submit_to_review: false
