workflows:
  ios_release:
    name: iOS Release (Pods repo-update)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    scripts:
      - name: Pre-build: Aggressive cache clear and pod repo rebuild
        script: |
          set -e
          echo "Removing all CocoaPods repos and caches..."
          rm -rf ~/.cocoapods/repos
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          rm -f ios/Podfile.lock
          echo "Setting up fresh pod repos and installing..."
          pod setup --silent
          cd ios
          pod install --repo-update
          cd ..
      - name: Flutter build iOS (no codesign)
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/xcarchive.zip
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ~/Library/Caches/CocoaPods
